FurryFriendRnR.UI/Controllers/OwnerAssetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FurryFriendRnR.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FurryFriendRnR.UI.Controllers
{
    public class OwnerAssetsController : Controller
    {
        private FurryFriendRnREntities db = new FurryFriendRnREntities();

        // GET: OwnerAssets
        [Authorize]
        public ActionResult Index()
        {
            string currentUserID = User.Identity.GetUserId();
            if (User.IsInRole("Admin") || User.IsInRole("Employee"))
            {
                var ownerAssets = db.OwnerAssets.Include(o => o.UserDetail);
                return View(ownerAssets.ToList());
            }
            else
            {
                var ownerAssets = db.OwnerAssets.Where(x => x.OwnerId == currentUserID).Include(a => a.UserDetail);
                return View(ownerAssets.ToList());
            }

            
        }

        // GET: OwnerAssets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            return View(ownerAsset);
        }

        // GET: OwnerAssets/Create
        [Authorize(Roles = "Admin,Family")]
        public ActionResult Create()
        {
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName");
            return View();
        }

        // POST: OwnerAssets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerAssetId,PetName,OwnerId,AssetPhoto,SpecialNotes,IsActive,DateAdded,PetBreed,RecordFile,PetBirthdate,Weight,Color,IsFixed,PetGender")]
        OwnerAsset ownerAsset, HttpPostedFileBase assetPhoto)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                string imgName = "noimg.jpg";
                if (assetPhoto != null)
                {
                    imgName = assetPhoto.FileName;
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".gif", ".png" };
                    if (goodExts.Contains(ext.ToLower()) && (assetPhoto.ContentLength <= 4194304))
                    {
                        imgName = Guid.NewGuid() + ext;
                        assetPhoto.SaveAs(Server.MapPath("~/Content/images/pet" + imgName));
                    }
                    else
                    {
                        imgName = "noimg.jpg";
                    }
                }

                ownerAsset.AssetPhoto = imgName;
                #endregion

                ownerAsset.OwnerId = User.Identity.GetUserId();
                db.OwnerAssets.Add(ownerAsset);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", ownerAsset.OwnerId);
            return View(ownerAsset);
        }

        // GET: OwnerAssets/Edit/5
        [Authorize(Roles = "Admin,Family")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", ownerAsset.OwnerId);
            return View(ownerAsset);
        }

        // POST: OwnerAssets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OwnerAssetId,PetName,OwnerId,AssetPhoto,SpecialNotes,IsActive,DateAdded,PetBreed,RecordFile,PetBirthdate,Weight,Color,IsFixed,PetGender")] OwnerAsset ownerAsset, HttpPostedFileBase assetPhoto)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                if (assetPhoto != null)
                {
                    string imgName = assetPhoto.FileName;
                    string ext = imgName.Substring(imgName.LastIndexOf("."));
                    string[] goodExts = { ".jpeg", ".jpg", ".gif", ".png" };
                    if (goodExts.Contains(ext.ToLower()) && (assetPhoto.ContentLength <= 4194304))
                    {
                        imgName = Guid.NewGuid() + ext;
                        assetPhoto.SaveAs(Server.MapPath("~/Content/images/" + imgName));
                        if (ownerAsset.AssetPhoto != null && ownerAsset.AssetPhoto != "noimg.jpg")
                        {
                            System.IO.File.Delete(Server.MapPath("~/Content/images/" + Session["currentImage"].ToString()));
                        }
                        ownerAsset.AssetPhoto = imgName;
                    }
                }          
                
                #endregion

                db.Entry(ownerAsset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ownerAsset);
        }

        // GET: OwnerAssets/Delete/5
        [Authorize(Roles = "Admin,Family")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            return View(ownerAsset);
        }

        // POST: OwnerAssets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);

            if (ownerAsset.AssetPhoto != null && ownerAsset.AssetPhoto != "noimg.jpg")
            {
                System.IO.File.Delete(Server.MapPath("~/Content/images/pet" + Session["currentImage"].ToString()));
            }

            db.OwnerAssets.Remove(ownerAsset);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FurryFriendRnR.UI/Views/OwnerAssets/Create.cshtml
@model FurryFriendRnR.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Add New Pet";
}

<div class="container">
    <h2><br />@ViewBag.Title</h2><hr />


    @using (Html.BeginForm("Create", "OwnerAssets", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.AssetPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" style="display:inline" name="assetPhoto" />
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.PetBreed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PetBreed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PetBreed, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.PetBirthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input name="PetBirthdate" type="text" id="datepicker" autocomplete="off">
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsFixed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsFixed)
                        @Html.ValidationMessageFor(model => model.IsFixed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PetGender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.PetGender)
                        @Html.ValidationMessageFor(model => model.PetGender, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
<br />


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FurryFriendRnR.UI/Views/OwnerAssets/Delete.cshtml
@model FurryFriendRnR.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Delete Pet";
}

<div class="container">
    <h2><br />@ViewBag.Title</h2><hr />

    <h4>Are you sure you want to delete this?</h4>
    <hr />
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PetName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AssetPhoto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AssetPhoto)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-primary" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>
<br />

FurryFriendRnR.UI/Views/OwnerAssets/Details.cshtml
@model FurryFriendRnR.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Pet Details";
}

<div class="container">
    <h2><br />@ViewBag.Title</h2><hr />

    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PetName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AssetPhoto)
            </dt>

            <dd>

                <img class="img-thumbnail" src="~/Content/images/pets/@Model.AssetPhoto" alt="@Model.PetName" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SpecialNotes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SpecialNotes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateAdded)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateAdded)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PetBreed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetBreed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RecordFile)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RecordFile)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PetBirthdate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetBirthdate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Weight)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Weight)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFixed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFixed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PetGender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetGender)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.OwnerAssetId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>
<br />

FurryFriendRnR.UI/Views/OwnerAssets/Edit.cshtml
@model FurryFriendRnR.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Edit Pets";
}

<div class="container">
    <h2><br />@ViewBag.Title</h2><hr />


    @using (Html.BeginForm("Edit", "OwnerAssets", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.OwnerAssetId)
            @Html.HiddenFor(model => model.AssetPhoto)

            <div class="form-group">
                @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AssetPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    Existing Photo: <img width="150" src="@Url.Content("~/Content/images/" + Model.AssetPhoto)" alt="Alternate Text" /> <br /><br />
                    Change Photo: <input type="file" name="assetPhoto" style="display:inline" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PetBreed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PetBreed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PetBreed, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RecordFile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RecordFile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RecordFile, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PetBirthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PetBirthdate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PetBirthdate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsFixed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsFixed)
                        @Html.ValidationMessageFor(model => model.IsFixed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PetGender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.PetGender)
                        @Html.ValidationMessageFor(model => model.PetGender, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
<br />



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FurryFriendRnR.UI/Views/OwnerAssets/Index.cshtml
@model IEnumerable<FurryFriendRnR.DATA.EF.OwnerAsset>
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "My Pets";
}

<div class="container">
    <h2><br />@ViewBag.Title</h2><hr />
    @if (User.IsInRole("Admin") || User.IsInRole("Family"))
    {
        <p>
            @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
        </p>
    }
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AssetPhoto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PetBreed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PetBirthdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PetGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsFixed)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img class="img-thumbnail" src="~/Content/images/pets/@item.AssetPhoto" alt="@item.PetName" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PetName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PetBreed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PetBirthdate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PetGender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsFixed)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.OwnerAssetId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.OwnerAssetId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.OwnerAssetId })
                </td>
            </tr>
        }

    </table>
</div>
<br />